FROM openjdk:24-jdk-slim
RUN apt update

RUN apt install -y iputils-ping

WORKDIR /app

COPY target/case-service-0.0.1-SNAPSHOT.jar case-service-0.0.1-SNAPSHOT.jar

CMD ["java","-jar","case-service-0.0.1-SNAPSHOT.jar"]

# docker build -t hsp/case-service:AN -f dockerfile .
# docker run -dit --rm -e DB_HOST=172.18.0.2 --name case-service --network Hospital-management hsp/case-service:AN          