FROM openjdk:24-jdk-slim
RUN apt update

RUN apt install -y iputils-ping

WORKDIR /app

COPY target/api-gateway-0.0.1-SNAPSHOT.jar api-gateway-0.0.1-SNAPSHOT.jar

CMD ["java","-jar","api-gateway-0.0.1-SNAPSHOT.jar"]

# docker build -t hsp/api-service:AN -f dockerfile .
# docker run -dit --rm -p 8080:8080 -e DB_HOST=172.18.0.2 --name api-service --network Hospital-management hsp/api-service:AN          