FROM openjdk:24-jdk-slim
RUN apt update

RUN apt install -y iputils-ping

WORKDIR /app

COPY target/directory-service-0.0.1-SNAPSHOT.jar directory-service-0.0.1-SNAPSHOT.jar

CMD ["java","-jar","directory-service-0.0.1-SNAPSHOT.jar"]

# docker build -t hsp/directory-service:AN -f dockerfile .
# docker run -dit --rm -e DB_HOST=172.18.0.2 --name directory-service --network Hospital-management hsp/directory-service:AN

# docker run -dit --rm --network Hospital-management --name mysql dnyanyog.org/mysql-custom:AN