FROM openjdk:24-jdk-slim
RUN apt update

RUN apt install -y iputils-ping

WORKDIR /app

COPY target/appointment-service-0.0.1-SNAPSHOT.jar appointment-service-0.0.1-SNAPSHOT.jar

CMD ["java","-jar","appointment-service-0.0.1-SNAPSHOT.jar"]

# docker build -t hsp/appointment-service:AN -f dockerfile .
# docker run -dit --rm -e DB_HOST=172.18.0.2 --name appointment-service --network Hospital-management hsp/appointment-service:AN          